I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/newGameScript.rpy", line 259, in script
    call quitGame
  File "game/newGameScript.rpy", line 259, in <module>
    call quitGame
NameError: name 'easein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/newGameScript.rpy", line 259, in script
    call quitGame
  File "C:\Users\sherwin\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 1359, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\sherwin\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\sherwin\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/newGameScript.rpy", line 259, in <module>
    call quitGame
NameError: name 'easein' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
02A2 game jam 1.0
Sun Jul 14 14:20:05 2024
